.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. betgenius_qt test_betgenius_qt
clean: FORCE
	$(MAKE) -C .. betgenius_qt_clean test_betgenius_qt_clean
check: FORCE
	$(MAKE) -C .. test_betgenius_qt_check
betgenius-qt betgenius-qt.exe: FORCE
	 $(MAKE) -C .. betgenius_qt
apk: FORCE
	$(MAKE) -C .. betgenius_qt_apk
